# import cx_Oracle
#
# # 连接到Oracle数据库
# dsn = cx_Oracle.makedsn(host='127.0.0.1', port=1521, sid='employeeheal')
# connection = cx_Oracle.connect(user='C##POXIAO', password='123456', dsn=dsn)
#
# # 创建游标
# cursor = connection.cursor()
#
#
# # 执行查询
# cursor.execute("SELECT * FROM table_name")
#
# # 获取查询结果
# result = cursor.fetchall()
#
# # 打印查询结果
# for row in result:
#     print(row)
#
#
# # 创建表
# create_table_sql = """
# CREATE TABLE SENTENCES_DATA (
#     ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
#     SENTENCE VARCHAR2(128),
#     SAME_DEPENDENCY NUMBER(1),
#     DEPENDENCY_PATH VARCHAR2(128),
#     PHRASE_TYPE VARCHAR2(32),
#     PHRASE_WORD VARCHAR2(32),
#     PHRASE_WORD_POS VARCHAR2(32),
#     QUESTION_WORD VARCHAR2(32),
#     QUESTION_WORD_POS VARCHAR2(32),
#     nummod
# obl:tmod
# advcl
# obl:agent
# conj
# obl
# cc
# obl:npmod
# cc:preconj
# cop
# nmod:poss
# punct
# xcomp
# expl
# aux
# obj
# acl
# ccomp
# acl:relcl
# dep
# appos
# nsubj:pass
# flat
# case
# amod
# root
# nmod:npmod
# aux:pass
# mark
# advcl:relcl
# advmod
# nmod
# iobj
# det:predet
# fixed
# det
# compound
# nsubj
# )
# """
#
# cursor.execute(create_table_sql)
#
# # # 插入数据
# # cursor.execute("INSERT INTO your_table (column1, column2) VALUES (:1, :2)", ("value1", "value2"))
# # connection.commit()
# #
# # # 更新数据
# # cursor.execute("UPDATE your_table SET column1 = :1 WHERE column2 = :2", ("new_value", "value2"))
# # connection.commit()
# #
# # # 删除数据
# # cursor.execute("DELETE FROM your_table WHERE column2 = :1", ("value2",))
# # connection.commit()
#
# # 关闭游标
# cursor.close()
#
# # 关闭连接
# connection.close()

from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text
Base = declarative_base()
engine = create_engine('oracle+cx_oracle://C##POXIAO:123456@127.0.0.1:1521/employeeheal')
Base.metadata.create_all(engine)  # 根据模型创建表结构，仅首次运行或表结构变化时需要

Session = sessionmaker(bind=engine)
session = Session()


stmt = session.execute(text("SELECT * FROM SENTENCES_DATA"))
rows = stmt.fetchall()

for row in rows:
    # 这里直接打印原始数据行，根据实际情况处理
    print(row)